[project]
name = "qiskit-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.5",
    "qiskit>=2.1.2",
    "qiskit-ibm-runtime>=0.41.1",
]
